name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: npm run build
      - name: Archive production build
        run: |
          cd dist
          zip -r ../globgram-alpha-build.zip .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: globgram-alpha-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
